import os
os.system('cls')
import time
print("Exoskeleton Hacked Client BETA")
print ("Please select an option from our instructions menu.")
print("Loading your saved key now.")
time.sleep(3)
f = open("key.txt", "r")
txt=f.read()
print(txt)
print("Loading Saved Script (script1.txt)")
script= open("script1.txt", "r")
printscr=script.read()
print(printscr)
print("Loading executor")
time.sleep(2)
print("Injecting into roblox process")
time.sleep(3)
print("Success!")
print("Please make sure ROBLOX is open now.")
time.sleep(3)
print("error 103: failed to connect to workspace")
print("make sure roblox is open and unpacthed for the exectutor")
print("logging error to crashlogs.txt")
with open('crashlogs.txt', 'w') as f:
    f.write("error 103 occured while"+printscr+"was running.")